# -*- coding: utf-8 -*-
"""Dicoding Proyek Analisis Data.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11J0bFoG8yzJbBAaRNNhtIDqD0sKSrVN2

# Proyek Analisis Data: [Input Nama Dataset]
- **Nama:** Muh. Fadhil Syam
- **Email:** Fasyamuhammad41@gmail.com
- **ID Dicoding:** faxyza

## Menentukan Pertanyaan Bisnis

- Bagaimana distribusi rating pelanggan berdasarkan waktu pengiriman dan kategori produk?
- Bagaimana perkembangan revenue bulanan selama periode pengamatan?
- Bagaimana Segmentasi customer berdasarkan nilai belanja
- Seberapa berpengaruh metode pembayaran terhadap nilai transaksi dan perilaku pembelian
- Seberapa berpengaruh performa pengiriman terhadap kepuasan pelanggan dan repeat order

## Import Semua Packages/Library yang Digunakan
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

"""## Data Wrangling

### Gathering Data
"""

customers_df = pd.read_csv("customers_dataset.csv")
customers_df.head(10)

"""**Insight:**
- Dataset berada pada level pelanggan (customer) dengan identifikasi unik menggunakan customer_unique_id.
- Variabel utama bersifat geografis dan relevan untuk analisis persebaran pelanggan.

"""

order_payments_df = pd.read_csv("order_payments_dataset.csv")
order_payments_df.head(10)

"""**Insight:**
- Dataset berada pada level pembayaran (order payment), di mana satu order dapat memiliki lebih dari satu tahapan pembayaran.
- Metode pembayaran didominasi oleh credit_card, dengan variasi jumlah cicilan (payment_installments).
- Dataset mendukung analisis perilaku pembayaran pelanggan dan preferensi metode pembayaran.

"""

order_items_df =  pd.read_csv("order_items_dataset.csv")
order_items_df.head(10)

"""**Insight:**
- Dataset berada pada level order item sehingga satu order dapat muncul beberapa kali.
- Variabel numerik utama adalah price dan freight_value yang relevan untuk analisis revenue.
- Tersedia informasi waktu pengiriman yang memungkinkan analisis SLA pengiriman.
- Dataset mencakup banyak seller dan produk unik.

"""

order_reviews_df =  pd.read_csv("order_reviews_dataset.csv")
order_reviews_df.head(10)

"""**Insight:**
- Data berada pada level order dan terhubung langsung dengan tabel order melalui order_id.
- Review_score dapat digunakan sebagai indikator kepuasan pelanggan.
- Tingginya missing value pada kolom komentar menunjukkan banyak ulasan berupa skor saja.
- Data teks memungkinkan eksplorasi sentimen pelanggan.
- Informasi timestamp mendukung analisis kecepatan respon terhadap ulasan.

"""

orders_df =  pd.read_csv("orders_dataset.csv")
orders_df.head(10)

"""**Insight:**
- Dataset berada pada level order dengan order_id unik per baris.  
- Tersedia banyak timestamp yang memungkinkan pembuatan fitur durasi (approval time, shipping time, delivery delay).  
- order_status dapat digunakan sebagai **label kategorikal** untuk analisis performa penyelesaian pesanan.  
- Perbandingan tanggal aktual vs estimasi mendukung analisis SLA pengiriman.  
- Fitur waktu pembelian dapat diturunkan menjadi variabel musiman dan tren permintaan.  

"""

products_df = pd.read_csv("products_dataset.csv")
products_df.head(10)

"""**Insight:**
- Dataset berada pada level produk, dengan product_id unik sebagai identifier utama.  
- Tersedia fitur teks seperti product_name_length dan product_description_length yang dapat digunakan sebagai proxy kompleksitas informasi produk.  
- Variabel`product_photos_qty berpotensi dianalisis terhadap performa penjualan atau ketertarikan pelanggan.  
- Fitur fisik produk (product_weight_g, product_length_cm, product_height_cm, product_width_cm) mendukung analisis logistik dan estimasi biaya pengiriman.  
- product_category_name memungkinkan segmentasi dan analisis performa berbasis kategori produk.

### Assessing Data

#### 1. Menilai data  customers_df
"""

customers_df.info()

"""**Insight:**
- Dataset menampilkan jumlah data dan type data
- jumlah data sesuai tidak ada yang hilang
- tapi ada kejanggalan ditipe data kolom (customer_zip_code_prefix), karena ini merupakan kode pos. dan bukan nilai numerik untuk perhitungan
"""

print("Jumlah duplikasi: ", customers_df.duplicated().sum())

"""**Insight:**

Tidak ada data yang terindikasi duplikat
"""

customers_df.describe()

"""**Insight:**

Tidak ada data yang yang keliru karena semestinya kolom (customer_zip_code_prefix) merupakan kode pos yang mestinya bukan bertipe data integer

#### 2. Menilai data order_payment_df
"""

order_payments_df.info()

"""**Insight & Kejanggalan:**
- Dataset berada pada level pembayaran, sehingga satu order_id dapat muncul lebih dari satu kali dan **perlu agregasi per order** untuk menghindari double counting saat analisis revenue.
- Seluruh kolom non-null, namun validasi logis tetap diperlukan (misalnya nilai payment_installments).
- payment_installments hanya relevan untuk metode tertentu (seperti credit_card) dan **harus difilter atau disesuaikan** saat analisis dan visualisasi.
"""

print("Jumlah duplikasi: ", order_payments_df.duplicated().sum())

"""**Insight:**

Tidak ada data yang terindikasi duplikat
"""

order_payments_df.describe()

"""**Insight:**
- Mayoritas transaksi memiliki payment_sequential = 1, menunjukkan sebagian besar order dibayar dalam satu tahap, meskipun terdapat hingga 29 tahap pembayaran pada kasus tertentu.
- Nilai median payment_installments adalah 1, menandakan sebagian besar transaksi tidak menggunakan cicilan, namun terdapat outlier hingga 24 kali cicilan.
- Distribusi payment_value bersifat right-skewed, dengan median sekitar 100 dan nilai maksimum sangat tinggi (13.664), sehingga berpotensi memengaruhi rata-rata.
- Terdapat nilai minimum 0 pada payment_installments dan payment_value yang perlu diverifikasi karena berpotensi tidak valid untuk analisis revenue.

#### 3. Menilai order_items_df
"""

order_items_df.info(10)

"""**Insight:**
- Dataset berada pada level order item, sehingga satu order dapat memiliki beberapa baris data.
- Variabel utama untuk analisis nilai transaksi adalah price dan freight_value.
- shipping_limit_date perlu dikonversi ke datetime untuk analisis waktu.
- Data perlu diagregasi ke level order agar tidak terjadi double counting pada analisis selanjutnya.

"""

print("jumlah duplikasi", order_items_df.duplicated().sum())

order_items_df.describe()

"""**Insight:**

Tidak ada data yang terindikasi duplikat
"""

order_items_df.describe()

"""**Insight:**
- Mayoritas order hanya memiliki satu item (order_item_id = 1).
- Distribusi price dan freight_value tidak normal dan memiliki outlier tinggi.
- Nilai freight_value = 0 perlu diverifikasi sebelum analisis lanjutan.

#### 4. Menilai order_reviews_df
"""

order_reviews_df.info()

"""**Insight:**
- Dataset berada pada level review per order, satu order dapat memiliki satu review.
- Variabel utama untuk analisis kepuasan adalah review_score.
- Kolom teks review tidak sepenuhnya terisi dan perlu penanganan missing value.
- Kolom waktu (review_creation_date, review_answer_timestamp) perlu dikonversi ke datetime untuk analisis temporal.

"""

order_reviews_df.isna().sum()

"""**Insight**

- Kolom review_comment_title memiliki kehilangan data yang sangat tinggi (87.656 baris).
- Kolom review_comment_message juga memiliki banyak data hilang (58.247 baris).
"""

print("Jumlah duplikasi: ", order_reviews_df.duplicated().sum())

"""**Insight:**

Tidak ada data yang terindikasi duplikat
"""

order_reviews_df.describe()

"""**Insight:**
- Mayoritas review_score bernilai 5.
- Rata-rata rating tinggi (≈4,1) menandakan kepuasan pelanggan sangat baik.
- Distribusi skor tidak merata dan condong ke nilai maksimum.

#### 5. Menilai order_datasets
"""

orders_df.info()

"""**Insight:**
- Dataset berada pada level order dengan total 99.441 data.
- Beberapa kolom waktu memiliki missing value, terutama order_delivered_carrier_date dan order_delivered_customer_date.
- Seluruh kolom bertipe object, sehingga kolom tanggal perlu dikonversi ke datetime untuk analisis waktu.


"""

print("Jumlah duplicate: ", orders_df.duplicated().sum())

"""**Insight:**

Tidak ada data yang terindikasi duplikat
"""

orders_df.describe()

"""**Insight:**
- Mayoritas order berstatus delivered.
- Terdapat beberapa missing value pada kolom waktu pengiriman.
- order_estimated_delivery_date memiliki banyak nilai yang sama dan perlu diperhatikan saat analisis keterlambatan.

#### 6. Menilai Data Product_df
"""

products_df.info()

"""**Insight:**
- Dataset berisi data produk dengan beberapa kolom memiliki missing value.
- Variabel numerik berkaitan dengan ukuran dan berat produk.

"""

print("Jumlah duplikasi: ", products_df.duplicated().sum())

"""**Insight:**

Tidak ada data yang terindikasi duplikat
"""

products_df.describe()

"""**Insight:**
- Sebagian besar produk memiliki 1 foto.
- Berat dan dimensi produk memiliki outlier yang tinggi.
- Terdapat nilai berat produk 0 yang perlu dicek kevalidannya.

### Cleaning Data

#### 1. Membersihkan data Customer_df
"""

customers_df["customer_zip_code_prefix"] = (
    customers_df["customer_zip_code_prefix"].astype(str)
)

customers_df.info()

"""**Insight:**
Untuk data customer_df permasalahannya hanyalah terletak pada jenis kolom customer_zip_code_prefix yang bertipe float diubah menjadi object
"""

customers_df.isnull().sum()

customers_df[customers_df.isnull().any(axis=1)]

customers_df.dropna(axis=0, inplace=True)

customers_df.info()

"""#### 2. Memberishkan data order_payment"""

order_payments_df.dropna(axis=0, inplace=True)

order_payments_df.info()

order_payments_df["payment_installments"] = (
    order_payments_df["payment_installments"].astype(int)
)


order_payments_df.info(
)

order_payments_df[order_payments_df.payment_installments.isna()]

order_payments_df[order_payments_df.payment_installments == order_payments_df.payment_installments.min()]

order_payments_df[order_payments_df.payment_value == order_payments_df.payment_value.min()]

order_payments_df[order_payments_df["payment_type"] == "not_defined"]

order_payments_df = order_payments_df[
    order_payments_df["payment_type"] != "not_defined"
]

products_df.info()

"""**Insight:**
- Data dengan payment_type = not_defined dihapus karena jumlahnya sangat sedikit dan tidak merepresentasikan metode pembayaran yang valid.
- Metode yang digunakan adalah drop untuk menghindari gangguan pada analisis pembayaran.
- Nilai minimum pada payment_installments dan payment_value tidak dihapus karena masih masuk akal dalam konteks proses transaksi (misalnya voucher atau promo).
- milihat dan menghapus nilai missing value dari data order_payment. karena hanya 1 data baris yang bernilai missing value jadi mentode yang digunakan untuk menanganinya adalah dropna (menhapusnya)
- merubah tipe data payment_installments yang awalnya float menjadi int

#### 3. Membersihkan data Order_items df
"""

order_items_df["shipping_limit_date"]=pd.to_datetime(
    order_items_df["shipping_limit_date"])

order_items_df.info()

order_items_df[order_items_df.isnull().any(axis=1)]

order_items_df.dropna(axis=0, inplace=True)

order_items_df.info()

order_items_df.describe()

"""**Insight :**

- mengganti tipe data shipping_limit_date yang awalnya object menjadi datetime
- menghapus missing value

#### 4. Membersihkan data order_reviews_df
"""

order_reviews_df[order_reviews_df.isnull().any(axis=1)]

date_time = ["review_creation_date", "review_answer_timestamp"]

for col in date_time:
  order_reviews_df[col] = pd.to_datetime(order_reviews_df[col])

order_reviews_df.info()

order_reviews_df[order_reviews_df.isnull().any(axis=1)]

"""**Insight: **

- data yang hilang pada kolom review_comment_title dan kolom review_comment_title tidak ditangani karena untuk analisis nantinya hanya menggunakan rating sehingga comment akan diabaikan
- mengubah tipe data yang berkaitan dengan tanggal dan waktu menjadi tipe data datetime, yang awalnya adalah object

#### 5. Membersihkan data order_df
"""

date_time2 = ["order_purchase_timestamp", "order_approved_at",
              "order_delivered_carrier_date", "order_delivered_customer_date", "order_estimated_delivery_date"]
for col in date_time2:
  orders_df[col] = pd.to_datetime(orders_df[col])

orders_df.info()

orders_df[orders_df.isnull().any(axis=1)]

orders_df.isnull().sum()

"""**Insight :**

- Merubah data yang awalnya object menjadi detetime
- karena didominasi data datetime sehingga untuk missing value diabaikan karena untuk kolom atau fitur yang digunakan hanyalah order_purchase_timestamp

#### 6. Membersihkan data Product_df
"""

products_df.isnull().sum()

products_df[products_df.isnull().any(axis=1)]

products_df.head()

"""## Exploratory Data Analysis (EDA)

### Explore data orders_df
"""

orders_df.describe(include="all")

orders_df["order_id"].nunique(), orders_df.shape[0]

orders_df.groupby("order_status").agg({
    "order_id": "count"
}).sort_values("order_id", ascending=False)

customer_spending = (
    orders_df
    .merge(order_revenue, on="order_id")
    .merge(customers_df, on="customer_id")
    .groupby("customer_unique_id")
    .agg(
        total_spent=("payment_value", "sum"),
        total_orders=("order_id", "nunique")
    )
)

customer_spending

review_delivery_df = (
    orders_df
    .merge(order_reviews_df, on="order_id", how="inner")
    .merge(order_items_df, on="order_id", how="inner")
    .merge(products_df, on="product_id", how="inner")
)

review_delivery_df["delivery_time"] = (
    review_delivery_df["order_delivered_customer_date"] -
    review_delivery_df["order_purchase_timestamp"]
).dt.days

rating_delivery = (
    review_delivery_df
    .groupby("delivery_time")
    .agg(
        avg_rating=("review_score", "mean"),
        total_orders=("order_id", "nunique")
    )
    .reset_index()
)

rating_delivery.head()

rating_category = (
    review_delivery_df
    .groupby("product_category_name")
    .agg(
        avg_rating=("review_score", "mean"),
        total_orders=("order_id", "nunique")
    )
    .sort_values("avg_rating", ascending=False)
)

rating_category.head(10)

order_revenue = (
    order_payments_df
    .groupby("order_id")["payment_value"]
    .sum()
    .reset_index()
)
order_revenue

monthly_revenue = (
    orders_df
    .merge(order_revenue, on="order_id", how="inner")
)

monthly_revenue["order_month"] = (
    monthly_revenue["order_purchase_timestamp"]
    .dt.to_period("M")
)

monthly_revenue_summary = (
    monthly_revenue
    .groupby("order_month")
    .agg(
        total_revenue=("payment_value", "sum"),
        total_orders=("order_id", "nunique")
    )
    .reset_index()
)

monthly_revenue_summary.head()

payment_behavior = (
    order_payments_df
    .groupby("payment_type")
    .agg(
        avg_payment_value=("payment_value", "mean"),
        avg_installments=("payment_installments", "mean"),
        total_transactions=("order_id", "count")
    )
    .sort_values("avg_payment_value", ascending=False)
)

payment_behavior

"""**Insight**
- Setiap order_id bersifat unik
- Satu baris merepresentasikan satu order
- Mayoritas order berstatus delivered (~97%)
- Tingkat pembatalan dan kegagalan order sangat rendah (<2%)
- Proses order umumnya selesai hingga pengiriman
- Estimasi pengiriman cenderung lebih lambat dari realisasi
- Periode data: September 2016 – Oktober 2018
- Missing value pada tanggal pengiriman sesuai status order

### Explore data customers_df dan orders_df
"""

orders_df.groupby("customer_id").agg({
    "order_id": "nunique"
}).rename(columns={"order_id": "total_orders"}).describe()

top_zip = (
    customers_df
    .groupby("customer_zip_code_prefix")
    .agg(
        total_customers=("customer_unique_id", "nunique")
    )
    .sort_values("total_customers", ascending=False)
    .head(10)
)

top_zip

"""**Insight – Pola Order per Customer**
- Setiap customer_id hanya memiliki 1 order
- Tidak ditemukan repeat order pada level customer_id
- Relasi data bersifat one-to-one antara customer dan order

**Insight – Distribusi Customer berdasarkan ZIP Code**
- Customer terkonsentrasi pada beberapa ZIP code tertentu
- ZIP code 22790 memiliki jumlah customer terbanyak
- Selisih jumlah customer antar ZIP code relatif kecil
- Terjadi pengelompokan customer berdasarkan wilayah geografis
- Area dengan customer tinggi berpotensi menjadi target promosi dan optimasi logistik

### Explore data order_paymets_df
"""

order_payments_df.groupby("order_id").size().describe()

order_payments_df.groupby("order_id").agg(
    total_payment_rows=("payment_value", "count"),
    total_payment_value=("payment_value", "sum")
).describe()

order_payments_df.groupby("payment_type").agg({
    "order_id": "nunique",
    "payment_value": ["mean", "sum"]
})

order_revenue = (
    order_payments_df
    .groupby("order_id")["payment_value"]
    .sum()
    .reset_index()
)

monthly_revenue = (
    orders_df
    .merge(order_revenue, on="order_id")
)

monthly_revenue["order_month"] = (
    monthly_revenue["order_purchase_timestamp"]
    .dt.to_period("M")
)

monthly_revenue_summary = (
    monthly_revenue
    .groupby("order_month")
    .agg(
        total_revenue=("payment_value", "sum"),
        total_orders=("order_id", "nunique")
    )
)

monthly_revenue_summary

order_revenue = (
    order_payments_df
    .groupby("order_id")["payment_value"]
    .sum()
    .reset_index()
)

monthly_revenue = (
    orders_df
    .merge(order_revenue, on="order_id")
)

monthly_revenue["order_month"] = (
    monthly_revenue["order_purchase_timestamp"]
    .dt.to_period("M")
)

monthly_revenue_summary = (
    monthly_revenue
    .groupby("order_month")
    .agg(
        total_revenue=("payment_value", "sum"),
        total_orders=("order_id", "nunique")
    )
)

monthly_revenue_summary

payment_repeat = (
    order_payments_df
    .merge(orders_df, on="order_id")
    .merge(customers_df, on="customer_id")
    .groupby("payment_type")
    .agg(
        avg_orders_per_customer=("customer_unique_id", "count")
    )
)

payment_repeat

payment_review = (
    order_payments_df
    .merge(order_reviews_df, on="order_id")
    .groupby("payment_type")
    .agg(
        avg_rating=("review_score", "mean"),
        avg_payment_value=("payment_value", "mean")
    )
)

payment_review

payment_impact = (
    order_payments_df
    .groupby("payment_type")
    .agg(
        avg_payment_value=("payment_value", "mean"),
        median_payment_value=("payment_value", "median"),
        total_revenue=("payment_value", "sum"),
        total_transactions=("order_id", "count")
    )
    .sort_values("total_revenue", ascending=False)
)

payment_impact

"""**Insight – Order Payments**
- Sebagian besar order memiliki satu metode pembayaran dengan nilai transaksi menengah
- Credit card mendominasi jumlah order dan total revenue
- Voucher digunakan untuk transaksi bernilai kecil
- Transaksi bernilai tinggi dan cicilan banyak hanya terjadi pada sebagian kecil order
- Metode pembayaran tidak menunjukkan perbedaan signifikan terhadap kepuasan pelanggan

### Explore data order_reviews_df
"""

order_reviews_df["order_id"].value_counts().head()

order_reviews_df.groupby("order_id").agg({
    "review_score": ["count", "mean", "min", "max"]
})

"""**Insight – Order Reviews**
- Sebagian kecil order memiliki lebih dari satu review, namun mayoritas order hanya memiliki satu review
- Review score per order bersifat konsisten (nilai min = max)
- Tidak ditemukan variasi rating dalam satu order
- Data review bersih dan valid untuk analisis kepuasan pelanggan per order

### Explore data order_items_df
"""

order_items_df.groupby("order_id").size().describe()

order_items_df.groupby("order_id").agg({
    "product_id": "nunique",
    "price": ["sum", "min", "max"],
    "freight_value": "sum"
}).describe()

category_per_order = order_items_df.merge(
    products_df[["product_id", "product_category_name"]],
    on="product_id"
).groupby("order_id")["product_category_name"].nunique()

category_per_order.describe()

"""**Insight – Order Items**
- Sebagian besar order hanya berisi 1 item
- Rata-rata item per order sekitar 1,14, dengan maksimum hingga 21 item
- Mayoritas order hanya memiliki 1 produk unik
- Nilai harga produk bersifat right-skewed, dengan sebagian kecil produk bernilai sangat tinggi
- Biaya pengiriman umumnya relatif kecil dibanding harga produk
- Hampir seluruh item memiliki satu kategori produk, menunjukkan klasifikasi produk konsisten

### explore data Products_df dan order_item_df
"""

print(products_df["product_id"].nunique())
print(order_items_df["product_id"].nunique())

merged_items = order_items_df.merge(
    products_df[["product_id", "product_category_name"]],
    on="product_id",
    how="left"
)

category_agg = merged_items.groupby("order_id").agg(
    total_items=("product_id", "nunique"),
    total_categories=("product_category_name", "nunique")
)

dominant_category = merged_items.groupby("order_id")[
    "product_category_name"
].apply(
    lambda x: x.mode().iloc[0] if not x.mode().empty else None
).to_frame("dominant_category")

category_eda = category_agg.merge(
    dominant_category,
    left_index=True,
    right_index=True
)

state_city = (
    customers_df
    .groupby(["customer_state", "customer_city"])
    .agg(
        total_customers=("customer_unique_id", "nunique")
    )
    .sort_values("total_customers", ascending=False)
)

state_city.head(10)

"""**Insight:**
**Insight – Produk & Distribusi Customer**
- Jumlah produk unik pada products_df dan order_items_df sama, menunjukkan seluruh produk tercatat pernah terjual
- Tidak ada produk di katalog yang tidak muncul dalam transaksi
- Customer terkonsentrasi pada kota-kota besar
- São Paulo memiliki jumlah customer tertinggi dan mendominasi secara signifikan
- Distribusi ini menunjukkan basis pelanggan kuat di wilayah perkotaan dan pusat ekonomi
- Kota besar berpotensi menjadi fokus utama strategi pemasaran dan logistik

### Explore data order_payments_df

### EDA all_df
"""

all_df = orders_df.merge(
    customers_df,
    on="customer_id",
    how="left"
)

payments_agg = order_payments_df.groupby("order_id").agg({
    "payment_value": "sum",
    "payment_type": "first",
    "payment_installments": "max"
}).reset_index()

all_df = all_df.merge(
    payments_agg,
    on="order_id",
    how="left"
)

all_df = all_df.merge(
    order_reviews_df[["order_id", "review_score"]],
    on="order_id",
    how="left"
)

order_product = order_items_df.merge(
    products_df[["product_id", "product_category_name"]],
    on="product_id",
    how="left"
)

product_category = order_product.groupby("order_id")["product_category_name"] \
    .agg(lambda x: x.mode().iloc[0] if not x.mode().empty else None) \
    .reset_index()

all_df = all_df.merge(
    product_category,
    on="order_id",
    how="left"
)

# Durasi pengiriman (hari)
all_df["delivery_time"] = (
    all_df["order_delivered_customer_date"] -
    all_df["order_purchase_timestamp"]
).dt.days

# Status keterlambatan
all_df["is_late"] = (
    all_df["order_delivered_customer_date"] >
    all_df["order_estimated_delivery_date"]
)

all_df.head()

all_df.info()

rating_delivery = (
    all_df
    .dropna(subset=["review_score", "is_late"])
    .groupby("is_late")
    .agg(
        avg_review_score=("review_score", "mean"),
        total_reviews=("review_score", "count")
    )
    .round(2)
)

rating_delivery

customer_spending = all_df.groupby("customer_unique_id")["payment_value"].sum()

customer_segment = pd.qcut(
    customer_spending,
    q=3,
    labels=["Low Value", "Mid Value", "High Value"]
)

customer_segment_summary = pd.DataFrame({
    "total_spending": customer_spending,
    "customer_segment": customer_segment
})

customer_segment_summary.head()

customer_spending = all_df.groupby("customer_unique_id")["payment_value"].sum()

customer_segment = pd.qcut(
    customer_spending,
    q=3,
    labels=["Low Value", "Mid Value", "High Value"]
)

customer_spending_summary = pd.DataFrame({
    "total_spending": customer_spending,
    "customer_segment": customer_segment
})

customer_spending_summary

payment_impact = all_df.groupby("payment_type").agg({
    "payment_value": "mean",
    "order_id": "count"
}).rename(columns={"order_id": "total_orders"})

payment_impact

repeat_order = all_df.groupby("customer_unique_id")["order_id"].count()

repeat_df = all_df.merge(
    repeat_order.rename("total_orders"),
    on="customer_unique_id",
    how="left"
)

delivery_review_repeat = repeat_df.groupby("is_late").agg({
    "review_score": "mean",
    "total_orders": "mean"
})

delivery_review_repeat

"""## 📌 Ringkasan Insight EDA

### 1️⃣ Rating Pelanggan, Waktu Pengiriman & Kategori Produk
- Order yang **terlambat dikirim** memiliki **rata-rata rating lebih rendah** dibandingkan order yang dikirim tepat waktu.
- Terdapat **perbedaan rating antar kategori produk**, dengan beberapa kategori menunjukkan rating yang konsisten lebih rendah.
- Hal ini mengindikasikan bahwa **performa logistik dan karakteristik kategori produk** berperan penting dalam membentuk kepuasan pelanggan.

---

### 2️⃣ Perkembangan Revenue Bulanan
- Revenue menunjukkan **fluktuasi dari waktu ke waktu**, yang mengindikasikan adanya **pola musiman**.
- Beberapa periode mencatat aktivitas transaksi yang lebih tinggi dibandingkan periode lainnya.
- Temuan ini dapat dimanfaatkan untuk **perencanaan promosi dan pengelolaan kapasitas operasional**.

---

### 3️⃣ Segmentasi Customer berdasarkan Nilai Belanja
- Customer dapat dikelompokkan menjadi **Low Value, Mid Value, dan High Value** berdasarkan total nilai belanja.
- **Sebagian kecil customer menyumbang kontribusi revenue yang signifikan**, sementara mayoritas berada pada segmen nilai belanja rendah hingga menengah.
- Segmentasi ini penting sebagai dasar **strategi retensi dan peningkatan loyalitas pelanggan**.

---

### 4️⃣ Pengaruh Metode Pembayaran terhadap Nilai Transaksi
- Metode pembayaran **credit card** cenderung memiliki **nilai transaksi rata-rata yang lebih tinggi** dibandingkan metode lainnya.
- Metode dengan frekuensi penggunaan tinggi tidak selalu menghasilkan nilai transaksi yang besar.
- Hal ini menunjukkan bahwa **metode pembayaran memengaruhi perilaku pembelian pelanggan**.

---

### 5️⃣ Performa Pengiriman terhadap Kepuasan & Repeat Order
- Order dengan keterlambatan pengiriman memiliki **rating pelanggan yang lebih rendah**.
- Pelanggan yang mengalami keterlambatan pengiriman cenderung memiliki **jumlah repeat order yang lebih sedikit**.
- Performa pengiriman berdampak langsung pada **kepuasan jangka pendek dan loyalitas pelanggan jangka panjang**.

## Visualization & Explanatory Analysis

### Pertanyaan 1: Bagaimana distribusi rating pelanggan berdasarkan waktu pengiriman dan kategori produk?
"""

plt.figure(figsize=(6,4))
sns.countplot(data=all_df, x="review_score")
plt.title("Distribusi Review Score")
plt.xlabel("Review Score")
plt.ylabel("Jumlah Order")
plt.show()

plt.figure(figsize=(6,4))
sns.boxplot(data=all_df, x="is_late", y="review_score")
plt.title("Review Score vs Keterlambatan Pengiriman")
plt.xlabel("Terlambat (True = Ya)")
plt.ylabel("Review Score")
plt.show()

top_category = (
    all_df["product_category_name"]
    .value_counts()
    .head(10)
    .index
)

plt.figure(figsize=(10,4))
sns.barplot(
    data=all_df[all_df["product_category_name"].isin(top_category)],
    x="product_category_name",
    y="review_score"
)
plt.title("Rata-rata Review Score per Kategori (Top 10)")
plt.xlabel("Kategori Produk")
plt.ylabel("Rata-rata Review Score")
plt.xticks(rotation=45)
plt.show()

plt.figure(figsize=(10,4))
sns.barplot(
    data=all_df[all_df["product_category_name"].isin(top_category)],
    x="product_category_name",
    y="review_score",
    hue="is_late"
)
plt.title("Review Score per Kategori berdasarkan Keterlambatan")
plt.xlabel("Kategori Produk")
plt.ylabel("Rata-rata Review Score")
plt.xticks(rotation=45)
plt.legend(title="Terlambat")
plt.show()

"""**Insight:**

Analisis visual dilakukan secara bertahap.
Distribusi review score dianalisis terlebih dahulu untuk memahami karakteristik data.
Selanjutnya, hubungan antara keterlambatan pengiriman dan review score dianalisis secara bivariate.
Analisis kemudian diperluas dengan memasukkan kategori produk untuk mengidentifikasi variasi kepuasan pelanggan antar kategori serta konsistensi dampak keterlambatan pengiriman.

### Pertanyaan 2: Bagaimana perkembangan revenue bulanan selama periode pengamatan?
"""

monthly_revenue = (
    all_df
    .assign(order_month=all_df["order_purchase_timestamp"].dt.to_period("M"))
    .groupby("order_month")["payment_value"]
    .sum()
    .reset_index()
)

monthly_revenue["order_month"] = monthly_revenue["order_month"].astype(str)

plt.figure(figsize=(10,4))
plt.plot(
    monthly_revenue["order_month"],
    monthly_revenue["payment_value"],
    marker="o"
)
plt.title("Perkembangan Revenue Bulanan")
plt.xlabel("Bulan")
plt.ylabel("Total Revenue")
plt.xticks(rotation=45)
plt.grid(True)
plt.show()

plt.figure(figsize=(10,4))
plt.bar(
    monthly_revenue["order_month"],
    monthly_revenue["payment_value"]
)
plt.title("Perbandingan Revenue Bulanan")
plt.xlabel("Bulan")
plt.ylabel("Total Revenue")
plt.xticks(rotation=45)
plt.show()

"""**Insight:**

Analisis revenue dilakukan menggunakan agregasi bulanan untuk menangkap tren pendapatan dari waktu ke waktu.
Hasil visualisasi menunjukkan bahwa revenue mengalami fluktuasi antar bulan, dengan beberapa periode menunjukkan peningkatan signifikan.
Pola ini mengindikasikan adanya kemungkinan seasonality atau pengaruh momen tertentu seperti promosi dan periode belanja besar.

### Pertanyaan 3: Bagaimana Segmentasi customer berdasarkan nilai belanja
"""

customer_spending = (
    all_df
    .groupby("customer_unique_id")["payment_value"]
    .sum()
    .reset_index()
    .rename(columns={"payment_value": "total_spending"})
)

upper_limit = customer_spending["total_spending"].quantile(0.95)

plt.figure(figsize=(6,4))
plt.hist(
    customer_spending.loc[
        customer_spending["total_spending"] <= upper_limit,
        "total_spending"
    ],
    bins=40
)
plt.title("Distribusi Total Belanja Customer (≤ P95)")
plt.xlabel("Total Belanja")
plt.ylabel("Jumlah Customer")
plt.show()

q60 = customer_spending["total_spending"].quantile(0.6)
q90 = customer_spending["total_spending"].quantile(0.9)

def segment_customer(x):
    if x <= q60:
        return "Low Value"
    elif x <= q90:
        return "Mid Value"
    else:
        return "High Value"

customer_spending["segment"] = customer_spending["total_spending"].apply(segment_customer)

segment_count = customer_spending["segment"].value_counts()

plt.figure(figsize=(5,4))
plt.bar(segment_count.index, segment_count.values)
plt.title("Jumlah Customer per Segment")
plt.ylabel("Jumlah Customer")
plt.show()

segment_revenue = (
    customer_spending
    .groupby("segment")["total_spending"]
    .sum()
)

plt.figure(figsize=(5,4))
plt.bar(segment_revenue.index, segment_revenue.values)
plt.title("Kontribusi Revenue per Segment Customer")
plt.ylabel("Total Revenue")
plt.show()

"""**Insight Utama:**
- Distribusi total belanja customer bersifat right-skewed, di mana mayoritas customer memiliki nilai belanja rendah, sementara sebagian kecil customer memiliki belanja sangat tinggi.
- Terdapat ketimpangan kontribusi revenue, di mana segmen kecil customer menyumbang porsi pendapatan yang signifikan.
- Segmentasi customer menjadi Low Value, Mid Value, dan High Value Customer menunjukkan bahwa:
  - Low Value Customer mendominasi jumlah pelanggan namun kontribusi revenue relatif kecil.
  - High Value Customer jumlahnya terbatas tetapi berkontribusi besar terhadap total revenue.

### Pertanyaan 4: Seberapa Berpengaruh Metode Pembayaran terhadap Nilai Transaksi dan Perilaku Pembelian?
"""

plt.figure(figsize=(6,4))
order_payments_df.boxplot(
    column="payment_value",
    by="payment_type",
    showfliers=False
)
plt.title("Distribusi Nilai Transaksi per Metode Pembayaran")
plt.suptitle("")
plt.xlabel("Metode Pembayaran")
plt.ylabel("Nilai Transaksi")
plt.show()

"""### Pertanyaan 5:  Seberapa berpengaruh performa pengiriman terhadap kepuasan pelanggan dan repeat order"""

delivery_df = orders_df.copy()

delivery_df["is_late"] = (
    delivery_df["order_delivered_customer_date"]
    > delivery_df["order_estimated_delivery_date"]
)

delivery_review_df = (
    delivery_df
    .merge(
        order_reviews_df[["order_id", "review_score"]],
        on="order_id",
        how="inner"
    )
)

delivery_review_df.groupby("is_late").agg(
    avg_review=("review_score", "mean"),
    median_review=("review_score", "median"),
    total_orders=("order_id", "count")
)

plt.figure(figsize=(4,4))
delivery_review_df.boxplot(
    column="review_score",
    by="is_late"
)
plt.title("Review Score vs Keterlambatan Pengiriman")
plt.suptitle("")
plt.xlabel("Terlambat")
plt.ylabel("Review Score")
plt.show()

late_ratio_df = (
    delivery_df
    .merge(customers_df, on="customer_id")
    .groupby("customer_unique_id")
    .agg(
        total_orders=("order_id", "nunique"),
        late_orders=("is_late", "sum")
    )
    .reset_index()
)

late_ratio_df["late_ratio"] = (
    late_ratio_df["late_orders"] / late_ratio_df["total_orders"]
)

late_ratio_df.groupby(
    pd.cut(late_ratio_df["late_ratio"], [0, 0.25, 0.5, 0.75, 1])
).agg(
    avg_orders=("total_orders", "mean"),
    customer_count=("customer_unique_id", "count")
)

"""**Insight**

Performa pengiriman memiliki pengaruh signifikan terhadap kepuasan pelanggan
dan perilaku repeat order. Order yang dikirim terlambat cenderung menerima
review score yang lebih rendah dibandingkan order yang dikirim tepat waktu.
Selain itu, customer dengan proporsi keterlambatan pengiriman yang lebih tinggi
menunjukkan rata-rata jumlah order yang lebih rendah. Hal ini mengindikasikan
bahwa pengalaman pengiriman yang buruk tidak hanya berdampak pada kepuasan
sesaat, tetapi juga menurunkan kecenderungan pelanggan untuk melakukan
pembelian ulang.

## Analisis Lanjutan (Opsional)
"""

orders_customer = orders_df.merge(
    customers_df[["customer_id", "customer_unique_id"]],
    on="customer_id",
    how="left"
)

snapshot_date = orders_customer["order_purchase_timestamp"].max() + pd.Timedelta(days=1)

rfm_base = orders_customer.groupby("customer_unique_id").agg({
    "order_purchase_timestamp": [
        lambda x: (snapshot_date - x.max()).days,  # Recency
        "count"                                    # Frequency
    ]
})

rfm_base.columns = ["Recency", "Frequency"]
rfm_base = rfm_base.reset_index()

payment_customer = orders_customer.merge(
    order_payments_df[["order_id", "payment_value"]],
    on="order_id",
    how="left"
)

monetary = payment_customer.groupby("customer_unique_id")["payment_value"].sum().reset_index()
monetary.columns = ["customer_unique_id", "Monetary"]

rfm = rfm_base.merge(monetary, on="customer_unique_id", how="left")
rfm.head()

rfm[["Recency", "Frequency", "Monetary"]].describe()

rfm["R_score"] = pd.qcut(
    rfm["Recency"],
    4,
    labels=[4,3,2,1]  # makin kecil recency = makin bagus
).astype(int)

rfm["F_score"] = pd.qcut(
    rfm["Frequency"].rank(method="first"),
    4,
    labels=[1,2,3,4]
).astype(int)

rfm["M_score"] = pd.qcut(
    rfm["Monetary"],
    4,
    labels=[1,2,3,4]
).astype(int)

def rfm_segment(row):
    if row["R_score"] == 4 and row["F_score"] == 4 and row["M_score"] == 4:
        return "Best Customer"
    elif row["F_score"] == 4 and row["M_score"] >= 3:
        return "Loyal Customer"
    elif row["R_score"] >= 3 and row["F_score"] <= 2:
        return "Potential Customer"
    elif row["R_score"] == 1 and row["F_score"] >= 3:
        return "At Risk Customer"
    else:
        return "Low Value Customer"

rfm["Segment"] = rfm.apply(rfm_segment, axis=1)

rfm["Segment"].value_counts()

rfm.groupby("Segment")["Monetary"].agg(
    total_revenue="sum",
    avg_revenue="mean",
    customer_count="count"
).sort_values("total_revenue", ascending=False)

segment_count = rfm["Segment"].value_counts()

plt.figure(figsize=(7,4))
segment_count.plot(kind="bar")
plt.title("Distribusi Customer Berdasarkan Segmen RFM")
plt.xlabel("Segmen Customer")
plt.ylabel("Jumlah Customer")
plt.xticks(rotation=30)
plt.show()

segment_revenue = rfm.groupby("Segment")["Monetary"].sum().sort_values(ascending=False)

plt.figure(figsize=(7,4))
segment_revenue.plot(kind="bar")
plt.title("Total Revenue Berdasarkan Segmen RFM")
plt.xlabel("Segmen Customer")
plt.ylabel("Total Revenue")
plt.xticks(rotation=30)
plt.show()

order_count = orders_df.merge(
    customers_df[["customer_id", "customer_unique_id"]],
    on="customer_id"
).groupby("customer_unique_id")["order_id"].count().reset_index()

order_count.columns = ["customer_unique_id", "total_orders"]

rfm_repeat = rfm.merge(order_count, on="customer_unique_id", how="left")

rfm_repeat.groupby("Segment")["total_orders"].mean().sort_values(ascending=False)

orders_delivery = orders_df.copy()

orders_delivery["delivery_delay"] = (
    orders_delivery["order_delivered_customer_date"]
    - orders_delivery["order_estimated_delivery_date"]
).dt.days

orders_delivery["is_late"] = orders_delivery["delivery_delay"] > 0

delivery_customer = orders_delivery.merge(
    customers_df[["customer_id", "customer_unique_id"]],
    on="customer_id"
)

rfm_delivery = rfm.merge(
    delivery_customer[["customer_unique_id", "is_late"]],
    on="customer_unique_id",
    how="left"
)

rfm_delivery.groupby("Segment")["is_late"].mean().sort_values(ascending=False)

repeat_by_segment = (
    rfm_repeat
    .groupby("Segment")["total_orders"]
    .mean()
    .sort_values(ascending=False)
)

plt.figure(figsize=(7,4))
repeat_by_segment.plot(kind="bar")
plt.title("Rata-rata Jumlah Order per Segmen RFM")
plt.xlabel("Segmen Customer")
plt.ylabel("Rata-rata Jumlah Order")
plt.xticks(rotation=30)
plt.show()

"""## Insight

- Performa pengiriman dan metode pembayaran berpengaruh terhadap kepuasan, repeat order, dan nilai transaksi pelanggan.
- Analisis RFM menunjukkan bahwa sebagian kecil pelanggan menyumbang porsi revenue terbesar, sementara mayoritas pelanggan memiliki nilai belanja rendah.
- Oleh karena itu, peningkatan kualitas pengiriman serta strategi retensi pelanggan bernilai tinggi menjadi kunci untuk pertumbuhan bisnis yang berkelanjutan.

## Conclusion

#### 1. Distribusi Rating Pelanggan berdasarkan Waktu Pengiriman dan Kategori Produk
Rating pelanggan cenderung lebih rendah pada order yang mengalami keterlambatan pengiriman dibandingkan order yang dikirim tepat waktu. Selain itu, terdapat perbedaan rata-rata rating antar kategori produk, yang mengindikasikan bahwa ekspektasi pelanggan dan pengalaman pengiriman dapat berbeda tergantung jenis produk.

#### 2. Perkembangan Revenue Bulanan selama Periode Pengamatan
Revenue bulanan menunjukkan fluktuasi sepanjang periode pengamatan, dengan adanya bulan-bulan tertentu yang memiliki transaksi lebih tinggi. Pola ini mengindikasikan kemungkinan adanya efek musiman dan periode dengan aktivitas belanja yang meningkat.

#### 3. Segmentasi Customer berdasarkan Nilai Belanja
Sebagian besar customer berada pada segmen dengan nilai belanja rendah, sementara hanya sebagian kecil customer yang berkontribusi besar terhadap total revenue. Hasil ini menunjukkan adanya ketimpangan kontribusi nilai antar customer dan menegaskan pentingnya fokus pada pelanggan bernilai tinggi.

#### 4. Pengaruh Metode Pembayaran terhadap Nilai Transaksi dan Perilaku Pembelian
Metode pembayaran tertentu, terutama kartu kredit, cenderung memiliki nilai transaksi rata-rata yang lebih tinggi dibandingkan metode lainnya. Hal ini menunjukkan bahwa metode pembayaran berperan dalam mendorong nilai belanja dan pola pembelian customer.

#### 5. Pengaruh Performa Pengiriman terhadap Kepuasan Pelanggan dan Repeat Order
Keterlambatan pengiriman berdampak negatif terhadap kepuasan pelanggan yang tercermin dari penurunan review score. Selain itu, customer yang sering mengalami keterlambatan pengiriman cenderung memiliki repeat order yang lebih rendah, menunjukkan bahwa performa pengiriman memengaruhi loyalitas pelanggan.
"""